apiVersion: v2
name: lm-container
description: A Helm chart for Logicmonitor's Kubernetes monitoring solutions
type: application
version: 1.1.0-rt02
maintainers:
  - name: LogicMonitor
    email: argus@logicmonitor.com
icon: https://vkumbhar94.github.io/helm-charts-qa-fork/lm_logo.png
kubeVersion: ">= 1.16.0-0"
dependencies:
  - name: argus
    # need to explicitly quote to make it string, else json schema fails
    version: "2.2.0-rt02"
    repository: https://vkumbhar94.github.io/helm-charts-qa-fork
    # uncomment to test umbrella chart in while developing
    # repository: file://../argus
    condition: argus.enabled
    tags:
      - logicmonitor
      - argus
      - monitoring
  - name: collectorset-controller
    # need to explicitly quote to make it string, else json schema fails
    version: "1.1.0-rt01"
    repository: https://vkumbhar94.github.io/helm-charts-qa-fork
    # uncomment to test umbrella chart in while developing
    # repository: file://../collectorset-controller
    condition: collectorset-controller.enabled
    tags:
      - logicmonitor
      - collectorset-controller
      - monitoring
  - condition: kube-state-metrics.enabled
    name: kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    version: 4.20.0
